
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrhulkdjzqyliwektgxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyaHVsa2RqenF5bGl3ZWt0Z3hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjQ1NDQsImV4cCI6MjA2MTQ0MDU0NH0.sAxSA4FvQqWTnFzq2kxCr8YJHY9ndkRB18VEDyZuFVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage
  }
});

// Maximum retries for bucket operations
const MAX_RETRIES = 3;

// Function to check if the applications bucket exists with retry mechanism
export const checkApplicationsBucket = async (retryCount = 0): Promise<boolean> => {
  try {
    console.log(`Checking if applications bucket is accessible (attempt ${retryCount + 1}/${MAX_RETRIES + 1})`);
    
    // First check if we can list the bucket
    const { data: buckets, error: bucketsError } = await supabase.storage.listBuckets();
    
    if (bucketsError) {
      console.error('Error listing buckets:', bucketsError);
      
      // Retry logic
      if (retryCount < MAX_RETRIES) {
        console.log(`Retrying in ${(retryCount + 1) * 1000}ms...`);
        await new Promise(resolve => setTimeout(resolve, (retryCount + 1) * 1000));
        return checkApplicationsBucket(retryCount + 1);
      }
      
      return false;
    }
    
    // Check if applications bucket exists in the list
    const applicationsBucketExists = buckets?.some(bucket => bucket.name === 'applications');
    console.log('Applications bucket exists in list:', applicationsBucketExists);
    
    if (!applicationsBucketExists) {
      console.error('Applications bucket does not exist');
      return false;
    }
    
    // Attempt to list files in the bucket to verify permissions
    const { data: files, error: filesError } = await supabase.storage
      .from('applications')
      .list();
      
    if (filesError) {
      console.error('Error accessing applications bucket:', filesError);
      
      // Retry logic for file listing
      if (retryCount < MAX_RETRIES) {
        console.log(`Retrying in ${(retryCount + 1) * 1000}ms...`);
        await new Promise(resolve => setTimeout(resolve, (retryCount + 1) * 1000));
        return checkApplicationsBucket(retryCount + 1);
      }
      
      return false;
    }
    
    console.log('Successfully accessed applications bucket');
    return true;
  } catch (error) {
    console.error('Unhandled error checking applications bucket:', error);
    
    // Retry logic for unhandled errors
    if (retryCount < MAX_RETRIES) {
      console.log(`Retrying after error in ${(retryCount + 1) * 1000}ms...`);
      await new Promise(resolve => setTimeout(resolve, (retryCount + 1) * 1000));
      return checkApplicationsBucket(retryCount + 1);
    }
    
    return false;
  }
};

// User roles management
export type UserRole = 'user' | 'admin';

export const getUserRole = async (): Promise<UserRole> => {
  try {
    // Check if the user is logged in
    const { data: sessionData } = await supabase.auth.getSession();
    if (!sessionData.session) {
      console.log('No active session, defaulting to user role');
      return 'user';
    }
    
    // Admin check based on specific email domains or predefined admin users
    const userEmail = sessionData.session.user.email;
    
    if (userEmail) {
      // Admin check based on email
      if (userEmail.includes('admin@') || userEmail.endsWith('@vcgeindhoven.nl')) {
        console.log('Admin role assigned based on email');
        return 'admin';
      }
      
      // Additional check against stored admin users in the database could be added here
    }
    
    // Default role
    return 'user';
    
  } catch (error) {
    console.error('Error determining user role:', error);
    return 'user'; // Default to regular user on error
  }
};
